recoder.testsuite.basic.syntax.WalkPositionTest
recoder.testsuite.basic.syntax.CloneTest
recoder.testsuite.basic.syntax.ParserPrinterTest
recoder.testsuite.basic.analysis.AnalysisReportTest
recoder.testsuite.basic.analysis.ModelRebuildTest
recoder.testsuite.basic.analysis.MemberXReferenceCompletenessTest
recoder.testsuite.basic.analysis.PackageXReferenceCompletenessTest
recoder.testsuite.basic.analysis.ReferenceCompletenessTest
recoder.testsuite.basic.analysis.TypeXReferenceCompletenessTest
recoder.testsuite.basic.analysis.LocalVariableXReferenceCompletenessTest
recoder.testsuite.basic.analysis.GetAllRelatedMethodsTest

