/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Mar 28 13:47:08 CET 2008
 */
package java.lang;

public class NullPointerException extends java.lang.RuntimeException
{

   /*@ public normal_behavior
     @   ensures message == null && cause == null;
     @   assignable message, cause;
     @*/
   public NullPointerException() { }
   
   
   /*@ public normal_behavior
     @   ensures message == arg0 && cause == null;
     @   assignable message, cause;
     @*/
   public NullPointerException(java.lang.String arg0) {
       super(arg0);
   }
}
