# .github/release.yml

# Documentation:
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - "Ignore in Changelog"
    authors:
      - octocat
      - dependabot
  categories:
    - title: Breaking Changes 🗲
      labels:
        - "Breaking Change"
        - "Breaks API"
    - title: Exciting New Features 🎉
      labels:
        - "Exciting New Feature"
    - title: Features
      labels:
        - "Feature"
    - title: Enhancement
      labels:
        - "Enhancement"
    - title: Bug Fixes
      labels:
        - ":lady_beetle: Bug"
        - "✋ Soundness"
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
