/* This file is part of KeY - https://key-project.org
 * KeY is licensed under the GNU General Public License Version 2
 * SPDX-License-Identifier: GPL-2.0-only */
package de.uka.ilkd.key.rule.lemma;

import java.util.Collection;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import de.uka.ilkd.key.proof.Goal;
import de.uka.ilkd.key.proof.Proof;
import de.uka.ilkd.key.proof.ProofAggregate;
import de.uka.ilkd.key.proof.init.InitConfig;
import de.uka.ilkd.key.proof.mgt.ProofEnvironment;
import de.uka.ilkd.key.rule.RewriteTaclet;
import de.uka.ilkd.key.rule.Taclet;
import de.uka.ilkd.key.taclettranslation.lemma.ProofObligationCreator;

import org.key_project.logic.Name;
import org.key_project.prover.sequent.PosInOccurrence;
import org.key_project.util.collection.DefaultImmutableSet;
import org.key_project.util.collection.ImmutableSet;

import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

/**
 * Proof-local registry of the taclets created by {@link LemmaTacletGenerator}s.
 *
 * <p>
 * The registry guarantees that per proof there is exactly one taclet instance (and one soundness
 * proof obligation) per lemma name. This makes repeated introductions of the same lemma — on
 * sibling branches, or after pruning and redoing the introduction — resolve to the already
 * existing taclet instead of creating duplicates. Reusing the identical taclet instance is also
 * required by the rule justification bookkeeping, which rejects re-registration of a distinct
 * rule under an existing name.
 */
@NullMarked
public final class GeneratedLemmaRegistry {

    private final Map<Name, GeneratedLemma> lemmas = new LinkedHashMap<>();

    private GeneratedLemmaRegistry() {
    }

    /**
     * returns the registry of the given proof, creating it on first access
     */
    public static GeneratedLemmaRegistry get(Proof proof) {
        GeneratedLemmaRegistry registry = proof.lookup(GeneratedLemmaRegistry.class);
        if (registry == null) {
            registry = new GeneratedLemmaRegistry();
            proof.register(registry, GeneratedLemmaRegistry.class);
        }
        return registry;
    }

    /**
     * returns the lemma generated by the given generator for the term at the given position. If a
     * lemma of the same name has been generated before, the existing one is returned; otherwise
     * the taclet is generated, its soundness proof obligation is created and registered in the
     * proof environment (if present), and the taclet is registered with a
     * {@link GeneratedLemmaJustification}.
     *
     * @param goal the current goal
     * @param pio the position of the term to be transformed
     * @param generator the generator computing the lemma taclet
     * @return the (possibly cached) generated lemma
     */
    public GeneratedLemma getOrCreate(Goal goal, PosInOccurrence pio,
            LemmaTacletGenerator generator) {
        final Proof proof = goal.proof();
        final RewriteTaclet taclet = generator.generate(goal, pio);

        final GeneratedLemma existing = lemmas.get(taclet.name());
        if (existing != null) {
            return existing;
        }

        final Proof soundnessProof = createSoundnessProof(taclet, proof);
        final GeneratedLemma lemma = new GeneratedLemma(taclet, soundnessProof);
        proof.getInitConfig().registerRule(taclet,
            new GeneratedLemmaJustification(generator.name(), soundnessProof));
        lemmas.put(taclet.name(), lemma);
        return lemma;
    }

    /**
     * returns the lemma registered under the given name, or {@code null} if there is none
     */
    public @Nullable GeneratedLemma lookup(Name name) {
        return lemmas.get(name);
    }

    /**
     * returns all lemmas generated for this proof so far
     */
    public Collection<GeneratedLemma> getLemmas() {
        return Collections.unmodifiableCollection(lemmas.values());
    }

    /**
     * Creates the soundness proof obligation for the given taclet, reusing the standard taclet
     * lemma machinery. The proof runs in a copy of the main proof's initial configuration; the
     * generated taclet itself is not part of that configuration, so it cannot be used to prove
     * itself.
     */
    private static Proof createSoundnessProof(RewriteTaclet taclet, Proof mainProof) {
        final InitConfig poConfig = mainProof.getInitConfig().deepCopy();
        final ImmutableSet<Taclet> tacletsToProve = DefaultImmutableSet.<Taclet>nil().add(taclet);

        final ProofAggregate po = new ProofObligationCreator().create(tacletsToProve,
            new InitConfig[] { poConfig }, DefaultImmutableSet.nil(), List.of());

        final ProofEnvironment env = mainProof.getEnv();
        if (env != null) {
            env.registerProof(new GeneratedLemmaPO(taclet.name(), po), po);
        }
        return po.getFirstProof();
    }
}
