/* This file is part of KeY - https://key-project.org
 * KeY is licensed under the GNU General Public License Version 2
 * SPDX-License-Identifier: GPL-2.0-only */
package de.uka.ilkd.key.rule.lemma;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import de.uka.ilkd.key.proof.Goal;
import de.uka.ilkd.key.proof.Proof;
import de.uka.ilkd.key.rule.RewriteTaclet;

import org.key_project.logic.Name;
import org.key_project.prover.rules.RuleAbortException;
import org.key_project.prover.sequent.PosInOccurrence;
import org.key_project.prover.sequent.SequentFormula;
import org.key_project.util.LRUCache;

import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

/**
 * Proof-local registry of the taclets created by {@link LemmaTacletGenerator}s.
 *
 * <p>
 * The registry guarantees that per proof there is exactly one taclet instance (and one soundness
 * proof obligation) per lemma name. This makes repeated introductions of the same lemma — on
 * sibling branches, or after pruning and redoing the introduction — resolve to the already
 * existing taclet instead of creating duplicates. Reusing the identical taclet instance is also
 * required by the rule justification bookkeeping, which rejects re-registration of a distinct
 * rule under an existing name.
 */
@NullMarked
public final class GeneratedLemmaRegistry {

    private static final int VETO_CACHE_SIZE = 1000;

    private final Map<Name, GeneratedLemma> lemmas = new LinkedHashMap<>();

    /**
     * Formulas for which lemma generation turned out not to be worthwhile (the aggregated
     * transformation is a semantic no-op). Vetoed formulas are not offered for introduction
     * again: without this, automation would not terminate. The veto is proof-local state — a
     * JVM-wide cache would leak vetoes into the replay of a reloaded proof, where a formula
     * vetoed late in the original run (in some branch context) would suppress the replay of an
     * introduction recorded earlier (in another context).
     */
    private final Map<SequentFormula, Boolean> vetoed = new LRUCache<>(VETO_CACHE_SIZE);

    private GeneratedLemmaRegistry() {
    }

    /**
     * marks the formula as not worth a lemma (see {@link #vetoed})
     */
    public synchronized void veto(SequentFormula formula) {
        vetoed.put(formula, Boolean.TRUE);
    }

    /**
     * returns true iff lemma generation has been vetoed for the given formula
     */
    public synchronized boolean isVetoed(SequentFormula formula) {
        return vetoed.get(formula) != null;
    }

    /**
     * returns the registry of the given proof, creating it on first access
     */
    public static GeneratedLemmaRegistry get(Proof proof) {
        GeneratedLemmaRegistry registry = proof.lookup(GeneratedLemmaRegistry.class);
        if (registry == null) {
            registry = new GeneratedLemmaRegistry();
            proof.register(registry, GeneratedLemmaRegistry.class);
        }
        return registry;
    }

    /**
     * returns the lemma generated by the given generator for the term at the given position. If a
     * lemma of the same name has been generated before, the existing one is returned; otherwise
     * the taclet is generated and registered with a {@link GeneratedLemmaJustification}. The
     * soundness proof obligation is <em>not</em> created here but lazily on first request (see
     * {@link GeneratedLemma#getOrCreateSoundnessProof()}), keeping it off the proof search path.
     *
     * @param goal the current goal
     * @param pio the position of the term to be transformed
     * @param generator the generator computing the lemma taclet
     * @return the (possibly cached) generated lemma
     */
    public synchronized GeneratedLemma getOrCreate(Goal goal, PosInOccurrence pio,
            LemmaTacletGenerator generator) {
        final Proof proof = goal.proof();
        final RewriteTaclet taclet = generator.generate(goal, pio);

        final GeneratedLemma existing = lemmas.get(taclet.name());
        if (existing != null) {
            // a name hit must mean identical content: formulas on different branches can be
            // equal in their printed form yet contain distinct proof-local symbol instances,
            // and handing out a taclet for the wrong instances would produce a rule that never
            // matches. Generators avoid this by making names unique per introduction where
            // necessary; this check turns any residual name aliasing into a visible abort.
            if (!existing.taclet().find().equals(taclet.find())) {
                throw new RuleAbortException("generated lemma name aliasing: " + taclet.name()
                    + " already denotes a lemma with different content"
                    + " (distinct proof-local symbols?)");
            }
            // pruning removes the justification together with the goal-locally introduced
            // taclet; re-register the identical justification instance in that case
            if (proof.getInitConfig().getJustifInfo()
                    .getJustification(existing.taclet()) == null) {
                proof.getInitConfig().registerRule(existing.taclet(), existing.justification());
            }
            return existing;
        }

        final GeneratedLemma lemma = new GeneratedLemma(taclet, proof, generator.name());
        // The registry owns the generated-lemma namespace of its proof. A justification entry
        // for this name that the registry does not know stems from a copied initial
        // configuration (InitConfig.deepCopy copies the justification map): e.g. when a proof
        // run in transparent mode is elaborated onto a fresh proof for transparent saving, the
        // fresh configuration inherits the original run's lemma justifications, and the
        // elaboration deliberately regenerates the same (replay-stable) names. Such foreign
        // entries are replaced by this proof's own.
        if (proof.getInitConfig().getJustifInfo().getJustification(taclet) != null) {
            proof.getInitConfig().getJustifInfo().removeJustificationFor(taclet);
        }
        proof.getInitConfig().registerRule(taclet, lemma.justification());
        lemmas.put(taclet.name(), lemma);
        return lemma;
    }

    /**
     * returns the lemma registered under the given name, or {@code null} if there is none
     */
    public synchronized @Nullable GeneratedLemma lookup(Name name) {
        return lemmas.get(name);
    }

    /**
     * returns all lemmas generated for this proof so far
     */
    public synchronized Collection<GeneratedLemma> getLemmas() {
        return Collections.unmodifiableCollection(lemmas.values());
    }

    /**
     * returns the lemmas generated for this proof whose soundness proof obligation has not yet
     * been discharged — either it has not been created, or it has been created but is not closed.
     * These are the lemmas that the proof is still closed only modulo (see
     * {@link de.uka.ilkd.key.proof.mgt.ProofCorrectnessMgt}).
     *
     * @return the missing lemmas, in generation order
     */
    public synchronized List<GeneratedLemma> getMissingLemmas() {
        final List<GeneratedLemma> missing = new ArrayList<>();
        for (final GeneratedLemma lemma : lemmas.values()) {
            if (!lemma.isProven()) {
                missing.add(lemma);
            }
        }
        return missing;
    }

    /**
     * groups the generated lemmas by their generator, preserving generation order within each
     * group
     *
     * @return a map from generator name to the lemmas it produced
     */
    public synchronized Map<Name, List<GeneratedLemma>> getLemmasByGenerator() {
        final Map<Name, List<GeneratedLemma>> byGenerator = new LinkedHashMap<>();
        for (final GeneratedLemma lemma : lemmas.values()) {
            byGenerator.computeIfAbsent(lemma.generatorName(), k -> new ArrayList<>()).add(lemma);
        }
        return byGenerator;
    }

    /**
     * groups the given lemmas by their content key (see {@link GeneratedLemma#contentKey()}), so
     * that lemmas denoting the same simplification (differing only in introduction point and
     * proof-local symbol renaming) are collapsed. The order of first appearance is preserved.
     *
     * @param lemmas the lemmas to group
     * @return a map from content key to the lemmas sharing it
     */
    public static Map<String, List<GeneratedLemma>> groupByContent(
            Collection<GeneratedLemma> lemmas) {
        final Map<String, List<GeneratedLemma>> byContent = new LinkedHashMap<>();
        for (final GeneratedLemma lemma : lemmas) {
            byContent.computeIfAbsent(lemma.contentKey(), k -> new ArrayList<>()).add(lemma);
        }
        return byContent;
    }

    /**
     * returns the registry of the given proof if one exists, without creating it; used by clients
     * that only inspect (e.g. the user interface) and must not attach a registry to proofs that
     * never generated a lemma
     *
     * @param proof the proof
     * @return the registry, or {@code null} if the proof has no generated lemmas
     */
    public static @Nullable GeneratedLemmaRegistry getIfPresent(Proof proof) {
        return proof.lookup(GeneratedLemmaRegistry.class);
    }
}
