/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Mar 28 13:47:08 CET 2008
 */
package java.util;

public interface Iterator
{
   //@ public instance ghost \seq seq;
   //@ public instance ghost \bigint index;
   
   //@ public instance invariant 0 <= index && index <= seq.length;

   /*@ public normal_behavior
     @ ensures \result == true <==> index < seq.length;
     @ assignable \strictly_nothing;
     @ determines \result \by seq.length, index;
     @*/
   public boolean hasNext();
   
   /*@ public normal_behavior
     @ requires index < seq.length;
     @ ensures \result == ((Object)seq[\old(index)]);
     @ ensures index == \old(index) + 1;
     @ assignable index;
     @ determines \result \by seq, index;
     @ determines index \by \itself;
     @*/
   public /*@nullable@*/ java.lang.Object next();
   
   public void remove();
}
