/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Mar 28 13:47:08 CET 2008
 */
package java.util;

public interface List extends java.util.Collection
{
   /*@ public normal_behavior
     @ requires arg0 == 0;
     @ ensures seq == \seq_concat(\seq_singleton(arg0), \old(seq));
     @ assignable seq;
     @ determines seq \by seq, arg0;
     @*/
   public void add(int arg0, java.lang.Object arg1);
   
   public boolean addAll(int arg0, java.util.Collection arg1);
   
   /*@ public normal_behavior
     @ requires 0 <= arg0 && arg0 < seq.length;
     @ ensures ((Object)seq[arg0]) == \result;
     @ assignable \nothing;
     @ determines \result \by seq, arg0;
     @*/
   public java.lang.Object get(int arg0);
   public java.lang.Object set(int arg0, java.lang.Object arg1);
   
   public int indexOf(java.lang.Object arg0);
   public int lastIndexOf(java.lang.Object arg0);
   
   /*@ public normal_behavior
     @ ensures \result.index == 0;
     @ ensures \result.seq == seq;
     @ ensures \fresh(\result) && \fresh(\result.*);
     @ ensures \result instanceof ListIteratorImpl;
     @ assignable \nothing;
     @ determines \result.seq \by seq;
     @ determines \result.index \by \nothing;
     @*/
   public java.util.ListIterator listIterator();
   public java.util.ListIterator listIterator(int arg0);
   public java.util.List subList(int arg0, int arg1);
}
