#!/bin/sh

#
# ProveRules documentation can be found at: key/doc/README.proveRules
#

LIST_TESTS_FLAG=--list-tests
FORK_MODE_FLAG=--fork-mode

list_help() {
    echo "Usage: runAllProofs [$LIST_TESTS_FLAG] | [ [$RELOAD_ENABLED_FLAG=<true|false>]"
    echo "                                       [$FORK_MODE_FLAG=<perTaclet|noFork>]"
    echo "                                       <groupNames> ]"
    echo "Examples: runAllProofs $FORK_MODE_FLAG=perFile newBook comprehensions"
    echo "          runAllProofs $LIST_TESTS_FLAG"
}

#
# Parse command line parameters
#

JAVA_ARGS=""

while [ "$#" -ne 0 ]
    do
    case $1 in
        --fork-mode=*)
        FORK_MODE=$(echo $1 | cut -d'=' -f 2)
        JAVA_ARGS="$JAVA_ARGS -Dkey.runallproofs.forkMode=$FORK_MODE"
        shift
        continue
        ;;
        $RELOAD_ENABLED_FLAG=*)
        RELOAD_ENABLED=$(echo $1 | cut -d'=' -f 2)
        JAVA_ARGS="$JAVA_ARGS -Dkey.runallproofs.reloadEnabled=$RELOAD_ENABLED"
        shift
        continue
        ;;
        $LIST_TESTS_FLAG)
        tools/testRunner.sh de.uka.ilkd.key.proof.runallproofs.ListRunAllProofsTestCases
        exit
        ;;
        -h|--help|-?)
        list_help
        exit
        ;;
        -*)
        echo Unrecognised option: $1
        exit
        ;;
        *)
        break
        ;;
    esac
    done
   
#
# Optionally, retrieve names of selected test cases
#

if [ "$#" -ne 0 ]
    then
    TEST_CASES=$1
    shift
    while [ "$#" -ne 0 ]
        do
        TEST_CASES="$TEST_CASES,$1"
        shift
        done
    JAVA_ARGS="$JAVA_ARGS -Dkey.runallproofs.testCases=$TEST_CASES"
fi

tools/testRunner.sh $JAVA_ARGS org.junit.runner.JUnitCore de.uka.ilkd.key.proof.proverules.ProveRulesTest

