#!/bin/sh

resolve_symlink  ()
{ 
   TARGET=`ls -l "$1"| awk '/\ ->\ /{print $NF}'`

   if [ -n "$TARGET" ] ; then
      RESULT="$TARGET"
      case "$RESULT" in
         /*) break ;;				# absolute symlink
         *)  RESULT=`dirname "$0"`/"$RESULT" ;;	# relative symlink
      esac
   else
      RESULT=$1
   fi

   echo "$RESULT"
}

UNAME=`uname -s 2>/dev/null | tr '[:upper:]' '[:lower:]'`
ARCH=`uname -pm 2>/dev/null | tr '[:upper:]' '[:lower:]' | tr ' ' '-'`

if [ -z "$JAVA_HOME" ] ; then
    JAVA=`which java`
    if [ -z "$JAVA" ] ; then
	echo "Cannot find JAVA. Please set your PATH or \$JAVA_HOME."
	exit 1
    fi
else
    if [ "$UNAME" = "darwin" ] ; then
	JRE=$JAVA_HOME/Home
	JAVA=$JRE/bin/java
# other OS
    else
	JRE=$JAVA_HOME/jre
	JAVA=$JRE/bin/java
    fi
fi
echo "Using JDK installation from:      $JAVA_HOME"


# For debugging reasons disable JIT (otherwise strace doesn't work)
JAVA_OPTIONS=""
#JAVA_OPTIONS=-classic

# Uncomment the following definition for remote debugging on port 1234
#JAVA_OPTIONS='-DKeyDebugFlag=on -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=1234'

#

if [ -z "$KEY_HOME" ] ; then
   KEY_HOME=`resolve_symlink "$0"`	# resolve symlink name
   KEY_HOME=`dirname "$KEY_HOME"`		# strip executable filename
   KEY_HOME=`cd "$KEY_HOME";pwd`	# and now expand the path to full
   KEY_HOME=`dirname "$KEY_HOME"`		# strip bin/ sirectory
fi
echo "Using KeY installation from:      $KEY_HOME"


if [ -z "$KEY_LIB" ] ; then
   KEY_LIB="$KEY_HOME/key-ext-jars"
else
echo "Using libraries from:             $KEY_LIB"
fi

export PATH

#
# KeY CLASSPATH
#

key_ext_jars="antlr.jar recoderKey.jar junit.jar"
keyclasspath="$KEY_HOME/system/binary/"

for i in $key_ext_jars ; do
    current_jar="$KEY_LIB/$i"
    if [ ! -f "$current_jar" ]
    then
       echo Cannot find $current_jar. 
       echo Copy or link the file into the
       echo $KEY_LIB directory.
       exit 1
    else
       keyclasspath="${keyclasspath}:$current_jar"
    fi
done



## jcoverage (stuff; optional)
keyclasspath="$KEY_HOME/system/instrumented/:${keyclasspath}:$KEY_LIB/jcoverage.jar"

#
#Function prints help message
#

list_help(){
  echo "./runTest [options] [filename]"
  echo "\nOptions for using this script"
  echo "  J-option: pass option to the JVM following the -J option convention of javac\n"
  echo "Debugging:\n"
  echo "  --K-keydebug: turn debugging on"
  echo "  --K-debugclassloader: switch the Debugclassloadflag on to load classes for debugging"
  echo "  --K-debugprefix <debugclass> : send debug output of debugclass to stadard out"
  echo "  --K-remotedebug <port>: turn remote debugging on; parameter for listening port"

  echo "Other:\n"

  echo "  --Khelp, -Kh	: prints this help message"
  echo "  --help	: prints help message of the KeY prover"

}

#
# KeY-specific command line options
#
keysysprops=""
keyoptions=""
while [ $# -ne 0 ]; do
    case $1 in
#     -K options for configuration options of KeY, such as debugmode, flags,
# remote debugging
	--Kh)
# 	    set ${1} #removes the minus from the option, s.t. it can be passed to key as option
	    list_help
	    exit;;
	--Khelp)
# 	    set ${1#--} #removes the minus from the option, s.t. it can be passed to key as option
	    list_help
	    exit;;
        --K-keydebug) keysysprops="${keysysprops}-DKeyDebugFlag=on "
            shift
            continue;;
        --K-debugclassloader)
keysysprops="${keysysprops}-DKeyDebugClassLoader=on
"
            shift
            continue;;

	--K-debugprefix) keysysprops="${keysysprops}-Dkey.debug.prefix=${2}"
	    shift
	    shift
	    continue;;


	--K-remotedebug) JAVA_OPTIONS="-Xdebug -Xnoagent -Djava.compiler=NONE
-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=${2}"
	    shift
	    shift
	    continue;;


# -J options follwing conventions of Java for -J options
	-J*)
	    option=${1#-J}
	    JAVA_OPTIONS="${JAVA_OPTIONS}${option} "
	    shift
	    continue;;
	  
	  *) break;;

    esac
done	


if [ ! -d "$HOME/.key" ]
then
mkdir "$HOME/.key"
fi

PATH=${PATH}:$KEY_LIB


if [ "" = "$1" ] 
then
    echo "No particular test case specified. All tests will be run."
    testcase=TestKey
else
    testcase=`echo $1 | tr '/' '.'`
fi

$JAVA $JAVA_OPTIONS $keysysprops \
-ea:de.uka.ilkd.key... -noverify -Djvm.dir=$JVM_DIR -Xms64m -Xmx2048m \
-Dkey.home="$KEY_HOME" \
-Djava.awt.headless=true \
-classpath "$keyclasspath" junit.textui.TestRunner $testcase 


