/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Mar 28 13:47:08 CET 2008
 */
package java.io;

public class IOException extends java.lang.Exception
{

   public IOException();
   public IOException(java.lang.String arg0);
   public IOException(java.lang.String arg0, java.lang.Throwable arg1);
   public IOException(java.lang.Throwable arg0);
}
