package de.uka.ilkd.key.testgen;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;


import de.uka.ilkd.key.gui.actions.CounterExampleAction;
import de.uka.ilkd.key.java.JavaNonTerminalProgramElement;
import de.uka.ilkd.key.java.JavaProgramElement;
import de.uka.ilkd.key.java.ProgramElement;
import de.uka.ilkd.key.java.Services;
import de.uka.ilkd.key.java.reference.MethodReference;
import de.uka.ilkd.key.java.statement.MethodBodyStatement;
import de.uka.ilkd.key.logic.JavaBlock;
import de.uka.ilkd.key.logic.Semisequent;
import de.uka.ilkd.key.logic.Sequent;
import de.uka.ilkd.key.logic.SequentFormula;
import de.uka.ilkd.key.logic.Term;
import de.uka.ilkd.key.proof.Goal;
import de.uka.ilkd.key.proof.Node;
import de.uka.ilkd.key.proof.Proof;
import de.uka.ilkd.key.smt.model.Heap;
import de.uka.ilkd.key.smt.model.Model;
import de.uka.ilkd.key.smt.model.ObjectVal;

public class TestCaseGenerator {
	
	Services services;
	Proof proof;
	static int fileCounter=0;
	boolean junitFormat;
	
	private static final String DONT_COPY = "aux"; //Classes of the Java environment needed by KeY can be placed in this subdirectory.
	private final String dontCopy;
    protected final String modDir;
    protected final String directory;
    String fileName;
	
	String TESTMETHOD = " public void  testcode0 () {";
	String POSTFIX = " }";
	
	public TestCaseGenerator(Goal  goal) {
		super();
		this.proof = CounterExampleAction.originalProof;
		this.services = proof.getServices();
		junitFormat = false;
		modDir = proof.getJavaModel().getModelDir();
		dontCopy = modDir + File.separator + DONT_COPY;
		this.directory = System.getProperty("user.home") + File.separator + "testFiles";
	}

	private boolean filterVal(String s){
		if(s.startsWith("#a")||s.startsWith("#s")||s.startsWith("#h")||s.startsWith("#l")||s.startsWith("#f")){
			return false;
		}
		else{
			return true;
		}
	}
	
	private ObjectVal getObject(Heap h,String name){
		if(h==null){
			return null;
		}
		for(ObjectVal o : h.getObjects()){
			if(o.getName().equals(name)){
				return o;
			}
		}
		return null;
	}
	
	public String generateJUnitTestCase(Model m){
		fileName = "TestGeneric"+fileCounter;
		String mut = getMUT();
		if(mut==null){
			mut = "<method under test> //Manually write a call to the method under test, because KeY could not determine it automatically.";
		}
		StringBuffer testCase = new StringBuffer();
		testCase.append(getFilePrefix() + "\n");
		testCase.append(getMainMethod()+"\n\n");
		testCase.append(TESTMETHOD+"\n");
		testCase.append("   //Test preamble: creating objects and intializing test data"+generateTestCase(m)+"\n\n");
		testCase.append("   //Calling the method under test\n   "+mut+"; \n");
		testCase.append(POSTFIX+"\n}");
		
		writeToFile(testCase);
		exportCodeUnderTest();
		
		fileCounter++;
		return testCase.toString();
	}
	
	public void writeToFile(StringBuffer sb){
		try
		{

			final File dir = new File(directory + modDir);
			if (!dir.exists()) {
			    dir.mkdirs();
			}
			final File pcFile = new File(dir, fileName + ".java");
			String path = pcFile.getAbsolutePath();
			System.out.println("Writing test file to:"+path);
			final FileWriter fw = new FileWriter(pcFile);
			final BufferedWriter bw = new BufferedWriter(fw);
			bw.write(sb.toString());
			bw.close();

			
		    //create a temporary file
//		    File logFile=new File("TestGeneric"+fileCounter+".java");
//		    BufferedWriter writer = new BufferedWriter(new FileWriter(logFile));
//		    writer.write (sb.toString());

		    //Close writer
		    //writer.close();
		} catch(Exception e)
		{
		    e.printStackTrace();
		}
	}

	
	private String getFilePrefix(){
		String res = "//This is a test driver generated by KeY 2.2. \n" +
				     "//Possible use cases: \n" +
				     "//  1. Compile and execute the main method with a JML runtime checker to test the method under test.\n" +
				     "//  2. Use a debuger to follow the execution of the method under test.\n\n\n";
		if(junitFormat){
			res += "import junit.framework.*;\n"
				+ " public class TestGeneric"+ fileCounter+ " extends junit.framework.TestCase {\n\n"
				+ " public TestGeneric"+fileCounter+"(){}\n"
				+ " public static junit.framework.TestSuite suite () {\n"
				+ "   junit.framework.TestSuite suiteVar;\n"
				+ "   suiteVar=new junit.framework.TestSuite (TestGeneric"+fileCounter+".class);\n"
				+ "   return  suiteVar;\n" 
				+ " }\n";
		}else{
			res += "public class TestGeneric"+ fileCounter+ "{ \n\n"
				+ " public TestGeneric"+fileCounter+"(){}\n";			
		}
		return res;
	}
	
	private String getMainMethod(){
		String res  = " public static void  main (java.lang.String[]  arg) {\n"
					+ "   TestGeneric"+fileCounter+" testSuiteObject;\n"
					+ "   testSuiteObject=new TestGeneric"+fileCounter+" ();\n"
					+ "   testSuiteObject.testcode0();\n" 
					+ " }";
		return res;
	}

	public String generateTestCase(Model m){
		
		List<Assignment> assignments = new LinkedList<Assignment>();
		
		Heap heap = null;
		for(Heap h : m.getHeaps()){
			if(h.getName().equals("heap")){
				heap = h;
				break;
			}
		}
		
				
		
		if(heap!=null){
			//create objects
			for(ObjectVal o : heap.getObjects()){
				if(o.getName().equals("#o0")){
					continue;
				}
				
				String type = o.getSort().name().toString();
				String right;				
				if(type.endsWith("[]")){
					right = "new "+type.substring(0, type.length()-2)+"["+o.getLength()+"]";
				}
				else{
					right = "new "+type+"()";
				}
				assignments.add(new Assignment(type, o.getName().replace("#", ""), right));
				
				
			}			
		}
		//init constants
		for(String c : m.getConstants().keySet()){
			String val = m.getConstants().get(c);
			if(filterVal(val) && !c.equals("null")){
				String type = "int";
				if(val.equals("true")||val.equals("false")){
					type = "boolean";
				}
				else if(val.startsWith("#o")){
					ObjectVal o = getObject(heap, val);
					if(o!=null){
						type = o.getSort().name().toString();
					}
					else{
						type = "Object";
					}
				}				
				val = val.replace("#", "");
				assignments.add(new Assignment(type,c,val));
			}
		}
		
		//init fields
		if(heap!=null){
			
			for(ObjectVal o : heap.getObjects()){
				if(o.getName().equals("#o0")){
					continue;
				}
				
				String name = o.getName().replace("#", "");
				
				for(String f : o.getFieldvalues().keySet()){
					if(f.contains("<") || f.contains(">")){
						continue;
					}
					String fieldName = f.substring(f.lastIndexOf(":")+1);
					fieldName = fieldName.replace("|", "");
					String val = o.getFieldvalues().get(f);
					if(val.contains("/")){
						val = val.substring(0, val.indexOf("/"));
					}
					val = val.replace("|", "");
					assignments.add(new Assignment(name+"."+fieldName, val));
				}
				
				for(int i = 0; i < o.getLength(); i++){
					String fieldName = "["+i+"]";
					String val = o.getArrayValue(i);
					if(val.contains("/")){
						val = val.substring(0, val.indexOf("/"));
					}
					assignments.add(new Assignment(name+fieldName, val));
				}				
			}			
		}
		
		
		String result = "";
		for(Assignment a : assignments){
			result+=a.toString();
		}
		
		
		
		return result;
	}

	public String getMUT(){
		System.out.println("Selected proof name:"+proof.name());
		
		Node root = proof.root();
		Sequent seq = root.sequent();
		Semisequent succ = seq.succedent();
		Iterator<SequentFormula> it = succ.iterator();
		String res = null;
		while(it.hasNext()){
			SequentFormula sf = it.next();
			Term form = sf.formula();
			res = findMUTInFormula(form);
			if(res!=null) break;
		}
		return res;
	}
	
	private String findMUTInFormula(Term form){
		JavaBlock jb = form.javaBlock();
		if(jb==null || jb.isEmpty()){
			for(int i = 0 ; i<form.arity();i++){
				String res = findMUTInFormula(form.sub(i));
				if(res!=null) return res;
			}
		}
		else {
			//System.out.println("---JavaBlock found:"+jb);
			JavaProgramElement jpe = jb.program();
			String res = findMUTInJavaPE(jpe);			
			if(res!=null) return res;
		}
		return null;
	}
	
	private String findMUTInJavaPE(JavaProgramElement jpe){
		if(jpe instanceof JavaNonTerminalProgramElement){
			JavaNonTerminalProgramElement jntpe = (JavaNonTerminalProgramElement) jpe;
			//System.out.println("JavaNonTerminalProgramElement " + jntpe.toSource());
			for(int i = 0; i<jntpe.getChildCount(); i++){
				ProgramElement pe = jntpe.getChildAt(i);
				//System.out.println("ProgramElement ("+pe.getClass()+") "+pe);
				if(pe instanceof MethodBodyStatement){
					MethodBodyStatement mbs = (MethodBodyStatement)pe;
					
					String methodCall = mbs.toString();
					//System.out.println("Method call:"+methodCall);
					int idx = methodCall.indexOf("@");
					if(idx>0){
						methodCall = methodCall.substring(0, idx);
					}
					//System.out.println("Method call:"+methodCall);					
					idx = methodCall.indexOf("(");
					String mc1 = methodCall.substring(0,idx);
					String mc2 = methodCall.substring(idx);
					mc2 = mc2.replace("_", " ");
					//System.out.println("mc1:"+mc1+"  mc2:"+mc2);
					methodCall = mc1 + mc2 ;
					
					//System.out.println("Method call:"+methodCall);
					return methodCall;
					
				}else if(pe instanceof JavaProgramElement){
					String res = findMUTInJavaPE((JavaProgramElement)pe);
					if(res!=null) return res;
				}
				
			}
		}
		return null;
	}


	protected void exportCodeUnderTest() {
	    try {
		// Copy the involved classes without modification
		copyFiles(modDir, directory + modDir);
	    } catch (final IOException e) {
		e.printStackTrace();
	    }

	}
	
	private void copyFiles(final String srcName, final String targName)
			throws IOException {
		// We don't want to copy the Folder with API Reference
		// Implementation
		if (srcName.equals(dontCopy)) {
			return;
		}
		// Create the File with given filename and check if it exists and if
		// it's readable
		final File srcFile = new File(srcName);
		if (!srcFile.exists()) {
			throw new IOException("FileCopy: " + "no such source file: "
					+ srcName);
		}
		if (!srcFile.canRead()) {
			throw new IOException("FileCopy: " + "source file is unreadable: "
					+ srcName);
		}
		if (srcFile.isDirectory()) {
			final String newTarget;
			if (srcName.equals(modDir)) {
				newTarget = targName;
			} else {
				newTarget = targName + File.separator + srcFile.getName();
			}
			for (final String subName : srcFile.list()) {
				copyFiles(srcName + File.separator + subName, newTarget);
			}
		} else if (srcFile.isFile()) {
			final File targDir = new File(targName);
			if (!targDir.exists()) {
				targDir.mkdirs();
			}
			final File targFile = new File(targDir, srcFile.getName());
			if (targFile.exists()) {
				if (!targFile.canWrite()) {
					throw new IOException("FileCopy: "
							+ "destination file is unwriteable: " + targName);
				}
			}
			FileInputStream src = null;
			FileOutputStream targ = null;
			try {
				src = new FileInputStream(srcFile);
				targ = new FileOutputStream(targFile);
				final byte[] buffer = new byte[4096];
				int bytesRead;

				while ((bytesRead = src.read(buffer)) != -1) {
					targ.write(buffer, 0, bytesRead); // write
				}
			} finally {
				if (src != null) {
					try {
						src.close();
					} catch (final IOException e) {
						;
					}
				}
				if (targ != null) {
					try {
						targ.close();
					} catch (final IOException e) {
						;
					}
				}
			}
		} else {
			throw new IOException("FileCopy: " + srcName
					+ " is neither a file nor a directory!");
		}
	}

}
