/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Mar 28 13:47:08 CET 2008
 */
package java.util;

public interface Set extends java.util.Collection
{

   public int size();
   
   public boolean isEmpty();
   
   public boolean contains(java.lang.Object arg0);
   
   public java.util.Iterator iterator();
   
   public java.lang.Object[] toArray();
   
   public java.lang.Object[] toArray(java.lang.Object[] arg0);
   
   public boolean add(java.lang.Object arg0);
   
   public boolean remove(java.lang.Object arg0);
   
   public boolean containsAll(java.util.Collection arg0);
   
   public boolean addAll(java.util.Collection arg0);
   
   public boolean retainAll(java.util.Collection arg0);
   
   public boolean removeAll(java.util.Collection arg0);
   
   public void clear();
   
   public boolean equals(java.lang.Object arg0);
   
   public int hashCode();
}
