<div style="width:100%; text-align:center">
    <div style="width: calc($proven$/$total$*100%); float:left;">proven</div>
    <div style="width: calc($lemmaLeft$/$total$*100%); float:left; white-space:nowrap;">lemma(s) left</div>
    <div style="width: calc($unproven$/$total$*100%); float:left;">unproven</div>
</div>
<div style="width:100%; background:#f1f1f1; color:white; text-align:center">
    <div style="width: calc($proven$/$total$*100%); background:#4CAF50; float:left;">$proven$</div>
    <div style="width: calc($lemmaLeft$/$total$*100%); background:#f48336; float:left;">$lemmaLeft$</div>
    <div style="width: calc($unproven$/$total$*100%); background:#f44336; float:left;">$unproven$</div>
</div>