[versions]
jspecify = "1.0.0"
eisop = "3.42.0-eisop5"

[libraries]
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.16" }

eisopCheckerQual = { module = "io.github.eisop:checker-qual", version.ref = "eisop" }
eisopUtil = { module = "io.github.eisop:checker-util", version.ref = "eisop" }
eisopChecker = { module = "io.github.eisop:checker", version.ref = "eisop" }

assertj = { module = "org.assertj:assertj-core", version = "3.27.3" }
logback = { module = "ch.qos.logback:logback-classic", version = "1.5.15" }
junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version = "5.11.4" }
junitParams = { module = "org.junit.jupiter:junit-jupiter-params", version = "5.11.4" }

yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version = "2.18.2" }
yamljsr = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version = "2.18.2" }

junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version = "5.11.4" }

javacc = { module = "net.java.dev.javacc:javacc", version = "4.0" }
antlr = { module = "org.antlr:antlr4", version = "4.13.2" }
antlrRuntime = { module = "org.antlr:antlr4-runtime", version = "4.13.2" }
miglayout = { module = "com.miglayout:miglayout-swing", version = "11.4.2" }

dockingFramesCommon = { module = "org.key-project:docking-frames-common", version = "1.1.3p1" }
dockingFramesCore = { module = "org.key-project:docking-frames-core", version = "1.1.3p1" }

stringtemplate = { module = "org.antlr:ST4", version = "4.3.4" }


[bundles]
junit = ["junitApi", "junitParams", "junitEngine"]
testing = ["junitApi", "junitParams", "junitEngine", "assertj", "logback", "yaml", "yamljsr"]

[plugins]
