// This is a test driver generated by KeY "3.0.0-dev (internal: 526b15139d2bd41fc3f7954a98f54ca90c057d3c)" (www.key-project.org).
// "TestGeneric0.java"
// @author Christoph Gladisch
// @author Mihai Herda
//
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Set;

class TestGeneric0 {
  public static final void main(String[] args) {
  }

  boolean testOracle(java.lang.Throwable exc, java.lang.Throwable _preexc, int[] a, int[] _prea,
      ArrayUtils self, ArrayUtils _preself, int[] b, int[] _preb, Set<Boolean> allBools,
      Set<Integer> allInts, Set<java.lang.Object> allObjects, Map<Object, Object> old) {
    return ((sub1(exc, _preexc, a, _prea, self, _preself, b, _preb, allBools, allInts, allObjects, old) && inv_javalangObject(self, exc, _preexc, a, _prea, self, _preself, b, _preb, allBools, allInts, allObjects, old)) && (exc == null));
  }

  boolean inv_javalangObject(java.lang.Object o, java.lang.Throwable exc,
      java.lang.Throwable _preexc, int[] a, int[] _prea, ArrayUtils self, ArrayUtils _preself,
      int[] b, int[] _preb, Set<Boolean> allBools, Set<Integer> allInts,
      Set<java.lang.Object> allObjects, Map<Object, Object> old) {
    return true;
  }

  boolean sub1(java.lang.Throwable exc, java.lang.Throwable _preexc, int[] a, int[] _prea,
      ArrayUtils self, ArrayUtils _preself, int[] b, int[] _preb, Set<Boolean> allBools,
      Set<Integer> allInts, Set<java.lang.Object> allObjects, Map<Object, Object> old) {
    for(int i : allInts) {
      if(!(!((0 <= i) && (i < a.length)) || (a[i] == b[i]))) {
        return false;
      }
    }
    return true;
  }
}
