/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Tue Apr 15 10:17:24 CEST 2008
 */
package java.lang;

public class NegativeArraySizeException extends java.lang.RuntimeException
{

   public NegativeArraySizeException() { super(); }
   public NegativeArraySizeException(java.lang.String arg0) { super(arg0); }
}
