blank_issues_enabled: true
contact_links:
  - name: FAQ
    url: https://www.key-project.org/docs/user/FAQ/
    about: Documentation 
  - name: KeY Discussions
    url: https://github.com/keyproject/key/discussions
    about: Please ask and answer questions here.
  - name: KeY Support
    url: support@key-project.org
    about: A confidential non-public channel
