/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Thu Mar 27 15:37:04 CET 2008
 */
package java.util;

public interface Iterator
{

   public boolean hasNext();
   public java.lang.Object next();
   public void remove();
}
