/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Mar 28 13:47:08 CET 2008
 */
package java.lang;

public class ArrayIndexOutOfBoundsException extends java.lang.IndexOutOfBoundsException
{

   public ArrayIndexOutOfBoundsException() { super(); }
   public ArrayIndexOutOfBoundsException(int arg0);
   public ArrayIndexOutOfBoundsException(java.lang.String arg0) { super(arg0); }
}
