/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Jan 31 13:16:59 CET 2014
 */
package java.lang;

public abstract class Number extends java.lang.Object implements java.io.Serializable
{

   public Number();
   public abstract int intValue();
   public abstract long longValue();
//   public abstract float floatValue();
//   public abstract double doubleValue();
   public byte byteValue();
   public short shortValue();
}
