// This file is part of KeY - Integrated Deductive Software Design
// Copyright (C) 2001-2007 Universitaet Karlsruhe, Germany
//                         Universitaet Koblenz-Landau, Germany
//                         Chalmers University of Technology, Sweden
//
// The KeY system is protected by the GNU General Public License. 
// See LICENSE.TXT for details.
//
//
/* Generated By:JavaCC: Do not edit this line. MyParserConstants.java */
package de.uka.ilkd.key.casetool.together.patterns.HelperClasses.MyParser;

public interface MyParserConstants {

  int EOF = 0;
  int PATTERNMOD = 5;
  int SCHEMA = 6;
  int COMMENT = 7;
  int MAPPINGS = 8;
  int SEVERALSUBCLASSES = 9;
  int MULTIINSTANCES = 10;
  int ADDSTRINGFIELD = 11;
  int ADDCLASSATTRIBUTE = 12;
  int ADDPARAMETER = 13;
  int ADDMETHOD = 14;
  int POSTCONDITION = 15;
  int PRECONDITION = 16;
  int PREPOSTCONDITION = 17;
  int INVARIANT = 18;
  int STATIC = 19;
  int PRIVATE = 20;
  int PUBLIC = 21;
  int PROTECTED = 22;
  int STRING1 = 23;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"patternmodification#\"",
    "\"schema#\"",
    "\"comment#\"",
    "\"mapping#\"",
    "\"canHaveSeveralSubclasses#\"",
    "\"canHaveMultipleInstances#\"",
    "\"addStringField#\"",
    "\"addClassAttribute#\"",
    "\"addParameter#\"",
    "\"addMethod#\"",
    "\"postcondition#\"",
    "\"precondition#\"",
    "\"prepostcondition#\"",
    "\"invariant#\"",
    "\"#static\"",
    "\"#private\"",
    "\"#public\"",
    "\"#protected\"",
    "<STRING1>",
    "\"#\"",
    "\"\\\'\"",
    "\"method#\"",
    "\"class#\"",
  };

}
