/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed May 14 11:55:42 CEST 2008
 */
package java.awt;

public interface LayoutManager2 extends java.awt.LayoutManager
{

   public void addLayoutComponent(java.awt.Component arg0, java.lang.Object arg1);
   public java.awt.Dimension maximumLayoutSize(java.awt.Container arg0);
   public float getLayoutAlignmentX(java.awt.Container arg0);
   public float getLayoutAlignmentY(java.awt.Container arg0);
   public void invalidateLayout(java.awt.Container arg0);
}
