/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Mar 28 13:47:08 CET 2008
 */
package java.lang;

public class ArithmeticException extends java.lang.RuntimeException
{

   public ArithmeticException() { super(); }
   public ArithmeticException(java.lang.String arg0) { super(arg0); }
}
