/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Thu Mar 27 15:37:04 CET 2008
 */
package java.lang;

public class ArrayIndexOutOfBoundsException extends java.lang.IndexOutOfBoundsException
{

   public ArrayIndexOutOfBoundsException();
   public ArrayIndexOutOfBoundsException(int arg0);
   public ArrayIndexOutOfBoundsException(java.lang.String arg0);
}
