/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Thu Mar 27 15:37:04 CET 2008
 */
package java.lang;

public interface Comparable
{

   public int compareTo(java.lang.Object arg0);
}
