/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Mar 28 13:47:08 CET 2008
 */
package java.lang;

public class Error extends java.lang.Throwable
{

   public Error();
   public Error(java.lang.String arg0);
   public Error(java.lang.String arg0, java.lang.Throwable arg1);
   public Error(java.lang.Throwable arg0);
}
