/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Mar 28 13:47:08 CET 2008
 */
package java.lang;

public class ExceptionInInitializerError
{

   public ExceptionInInitializerError();
   public ExceptionInInitializerError(java.lang.Throwable arg0);
   public ExceptionInInitializerError(java.lang.String arg0);
   public java.lang.Throwable getException();
   public java.lang.Throwable getCause();
}
