/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Thu Mar 27 15:37:04 CET 2008
 */
package java.lang;

public class Exception extends java.lang.Throwable
{

   public Exception();
   public Exception(java.lang.String arg0);
   public Exception(java.lang.String arg0, java.lang.Throwable arg1);
   public Exception(java.lang.Throwable arg0);
}
