/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Mar 28 13:47:08 CET 2008
 */
package java.lang;

public class NoClassDefFoundError
{

   public NoClassDefFoundError();
   public NoClassDefFoundError(java.lang.String arg0);
}
