/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Thu Mar 27 15:37:04 CET 2008
 */
package java.lang;

public class NullPointerException extends java.lang.RuntimeException
{

   public NullPointerException();
   public NullPointerException(java.lang.String arg0);
}
