/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Thu Mar 27 15:37:04 CET 2008
 */
package java.lang;

public class Object extends java.lang.Object
{

   public Object();
// public final java.lang.Class getClass();
   public int hashCode();
   public boolean equals(java.lang.Object arg0);
   protected java.lang.Object clone() throws java.lang.CloneNotSupportedException;
   public java.lang.String toString();
   public final void notify();
   public final void notifyAll();
   public final void wait(long arg0) throws java.lang.InterruptedException;
   public final void wait(long arg0, int arg1) throws java.lang.InterruptedException;
   public final void wait() throws java.lang.InterruptedException;
   protected void finalize() throws java.lang.Throwable;
}
