/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Thu Mar 27 15:37:04 CET 2008
 */
package java.lang;

public class RuntimeException extends java.lang.Exception
{

   public RuntimeException();
   public RuntimeException(java.lang.String arg0);
   public RuntimeException(java.lang.String arg0, java.lang.Throwable arg1);
   public RuntimeException(java.lang.Throwable arg0);
}
