/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Mar 28 13:47:08 CET 2008
 */
package java.lang;

public class Throwable extends java.lang.Object implements java.io.Serializable
{

   public Throwable();
   public Throwable(java.lang.String arg0);
   public Throwable(java.lang.String arg0, java.lang.Throwable arg1);
   public Throwable(java.lang.Throwable arg0);
   public java.lang.String getMessage();
   public java.lang.String getLocalizedMessage();
   public java.lang.Throwable getCause();
   public java.lang.Throwable initCause(java.lang.Throwable arg0);
   public java.lang.String toString();
   public void printStackTrace();
// public void printStackTrace(java.io.PrintStream arg0);
// public void printStackTrace(java.io.PrintWriter arg0);
   public java.lang.Throwable fillInStackTrace();
// public java.lang.StackTraceElement[] getStackTrace();
// public void setStackTrace(java.lang.StackTraceElement[] arg0);
}
