/* This file is part of KeY - https://key-project.org
 * KeY is licensed under the GNU General Public License Version 2
 * SPDX-License-Identifier: GPL-2.0-only */

// generated by famous KeY -- Tool

package de.uka.ilkd.key.pp;

import java.io.Writer;

import de.uka.ilkd.key.java.PrettyPrinter;
import de.uka.ilkd.key.rule.inst.SVInstantiations;

public class ProgramPrinter extends PrettyPrinter {

    /**
     * creates the program printer
     *
     * @param writer
     *        the Writer to print in, may be <code>null</code>.
     */
    public ProgramPrinter(Writer writer) {
        super(writer);
    }

    public ProgramPrinter(Writer writer, SVInstantiations svi) {
        super(writer, svi);
    }

    public ProgramPrinter() {
        super(null);
    }

    public ProgramPrinter(Writer w, boolean b,
            SVInstantiations instantiations) {
        super(w, b, instantiations);
    }
}
