// This file is part of KeY - Integrated Deductive Software Design
// Copyright (C) 2001-2005 Universitaet Karlsruhe, Germany
//                         Universitaet Koblenz-Landau, Germany
//                         Chalmers University of Technology, Sweden
//
// The KeY system is protected by the GNU General Public License. 
// See LICENSE.TXT for details.
//
//

/* Generated by Together */

package de.uka.ilkd.key.casetool.together.scripts.menuextension;

import com.togethersoft.openapi.ide.window.IdeWindowManager;

import de.uka.ilkd.key.gui.ChoiceSelector;


public class GlobalMenuPoint1_5 implements GlobalMenu{
    private static int selection=0;
    public String getMenuEntry(){
	return "Taclet Options Defaults";
    }

    public void run(IdeWindowManager winMan){
	ChoiceSelector selector = new 
	    ChoiceSelector();
    }
   

}
