/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed May 14 11:55:36 CEST 2008
 */
package java.awt.event;

public interface ActionListener extends java.util.EventListener
{

   public void actionPerformed(java.awt.event.ActionEvent arg0);
}
