/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Mar 28 13:47:08 CET 2008
 */
package java.lang;

public class Exception extends java.lang.Throwable
{

   public Exception() { super(); }
   public Exception(java.lang.String arg0) { super(arg0); }
   public Exception(java.lang.String arg0, java.lang.Throwable arg1) { super(arg0, arg1); }
   public Exception(java.lang.Throwable arg0) { super(arg0); }
}
