/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Jan 31 13:24:50 CET 2014
 */
package java.lang;

public class NumberFormatException extends java.lang.IllegalArgumentException
{

   public NumberFormatException() { super(); }
   public NumberFormatException(java.lang.String arg0) { super(arg0); }
}
