/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed May 14 11:55:45 CEST 2008
 */
package java.awt;

public class Dimension extends java.awt.geom.Dimension2D implements java.io.Serializable
{
   public int width;
   public int height;

   public Dimension();
   public Dimension(java.awt.Dimension arg0);
   public Dimension(int arg0, int arg1);
   public double getWidth();
   public double getHeight();
   public void setSize(double arg0, double arg1);
   public java.awt.Dimension getSize();
   public void setSize(java.awt.Dimension arg0);
   public void setSize(int arg0, int arg1);
   public boolean equals(java.lang.Object arg0);
   public int hashCode();
   public java.lang.String toString();
}
