/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Wed May 14 11:55:43 CEST 2008
 */
package java.lang;

public class IllegalStateException extends java.lang.RuntimeException
{

   public IllegalStateException();
   public IllegalStateException(java.lang.String arg0);
   public IllegalStateException(java.lang.String arg0, java.lang.Throwable arg1);
   public IllegalStateException(java.lang.Throwable arg0);
}
