/* This file is part of KeY - https://key-project.org
 * KeY is licensed under the GNU General Public License Version 2
 * SPDX-License-Identifier: GPL-2.0-only */
package org.key_project.ncore.java;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.lang.reflect.AccessFlag;
import java.util.*;

import de.uka.ilkd.key.java.ast.*;
import de.uka.ilkd.key.java.ast.ccatch.*;
import de.uka.ilkd.key.java.ast.declaration.*;
import de.uka.ilkd.key.java.ast.expression.*;
import de.uka.ilkd.key.java.ast.expression.literal.*;
import de.uka.ilkd.key.java.ast.expression.operator.*;
import de.uka.ilkd.key.java.ast.reference.*;
import de.uka.ilkd.key.java.ast.statement.*;
import de.uka.ilkd.key.logic.ProgramConstruct;
import de.uka.ilkd.key.logic.ProgramElementName;
import de.uka.ilkd.key.logic.ProgramPrefix;
import de.uka.ilkd.key.logic.VariableNamer;
import de.uka.ilkd.key.logic.op.*;
import de.uka.ilkd.key.rule.AbstractProgramElement;
import de.uka.ilkd.key.rule.metaconstruct.*;

import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.type.ClassOrInterfaceType;

/**
 *
 * @author Alexander Weigl
 * @version 1 (4/11/26)
 */
public class ReadAllHierarchy {
    static Set<Class<?>> allClasses = new HashSet<>(List.of(
        ExecutionContext.class,
        ArrayLength.class,
        SuperReference.class,
        ProgramTransformer.class,
        Instanceof.class,
        ArrayInitializer.class,
        ProgramSV.class,
        Exec.class,
        ThisReference.class,
        MethodCall.class,
        FieldDeclaration.class,
        ForInitUnfoldTransformer.class,
        SchemaTypeReference.class,
        EnhancedForElimination.class,
        IProgramVariable.class,
        ClassDeclaration.class,
        ContextStatementBlock.class,
        MethodReference.class,
        SpecialConstructorCall.class,
        FloatLiteral.class,
        TypeDeclaration.class,
        PackageReference.class,
        SuperConstructorReference.class,
        SchematicFieldReference.class,
        TypeCast.class,
        ForToWhile.class,
        LabelJumpStatement.class,
        ReattachLoopInvariant.class,
        Switch.class,
        InterfaceDeclaration.class,
        Break.class,
        TypeDeclaration.class,
        CcatchContinueWildcardParameterDeclaration.class,
        InitArrayCreation.class,
        TypeRef.class,
        EnumClassDeclaration.class,
        CatchAllStatement.class,
        LoopInit.class,
        TypeReferenceImp.class,
        MethodOrConstructorReference.class,
        ForToWhile.class,
        FieldReference.class,
        ForToWhile.class,
        MultipleVarDecl.class,
        EnumClassDeclaration.class,
        TypeDeclaration.class,
        Break.class,
        Conditional.class,
        JavaDeclaration.class,
        CompilationUnit.class,
        PostWork.class,
        ReattachLoopInvariant.class,
        ClassDeclaration.class,
        ConstructorDeclaration.class,
        ThisReference.class,
        UnwindLoop.class,
        ArrayReference.class,
        InterfaceDeclaration.class,
        UnwindLoop.class,
        EnhancedForElimination.class,
        MethodCall.class,
        PostWork.class,
        LocalVariableDeclaration.class,
        ReferencePrefix.class,
        ExactInstanceof.class,
        EvaluateArgs.class,
        FieldReference.class,
        EnumClassDeclaration.class,
        ExpandMethodBody.class,
        Switch.class,
        Unpack.class,
        ContextStatementBlock.class,
        SpecialConstructorReference.class,
        Exec.class,
        ConstructorCall.class,
        VariableNamer.IndProgramElementName.class,
        IsStatic.class,
        ProgramSV.class,
        ArrayLength.class,
        BranchStatement.class,
        ProgramSV.class,
        ForInitUnfoldTransformer.class,
        PackageReference.class,
        Operator.class,
        Label.class,
        TypeDeclaration.class,
        SwitchToIf.class,
        ExpandMethodBody.class,
        ExpandMethodBody.class,
        Instanceof.class,
        Switch.class,
        TypeReference.class,
        CcatchContinueLabelParameterDeclaration.class,
        ForInitUnfoldTransformer.class,
        Throws.class,
        SuperArrayDeclaration.class,
        ExpandMethodBody.class,
        ProgramConstruct.class,
        ExactInstanceof.class,
        SuperArrayDeclaration.class,
        SchemaTypeReference.class,
        TypeReferenceImp.class,
        ForToWhile.class,
        ConstructorCall.class,
        FieldDeclaration.class,
        EvaluateArgs.class,
        ParenthesizedExpression.class,
        ConstructorCall.class,
        EnumClassDeclaration.class,
        SuperConstructorReference.class,
        PackageSpecification.class,
        ClassInitializer.class,
        ProgramSV.class,
        InitArray.class,
        UnwindLoop.class,
        ExecutionContext.class,
        ProgramConstruct.class,
        New.class,
        ArrayPostDecl.class,
        For.class,
        MethodFrame.class,
        ForUpdates.class,
        SuperArrayDeclaration.class,
        Unpack.class,
        ArrayLengthReference.class,
        LoopInitializer.class,
        ClassDeclaration.class,
        DoBreak.class,
        BranchStatement.class,
        InterfaceDeclaration.class,
        JavaDeclaration.class,
        SetStatement.class,
        Finally.class,
        Ccatch.class,
        EnhancedForElimination.class,
        PassiveExpression.class,
        ArrayReference.class,
        MethodDeclaration.class,
        SwitchToIf.class,
        For.class,
        ConstructorCall.class,
        ExpressionJumpStatement.class,
        Case.class,
        LoopScopeBlock.class,
        IntLiteral.class,
        ThisReference.class,
        ProgramTransformer.class,
        Import.class,
        SpecialConstructorCall.class,
        LabelJumpStatement.class,
        TypeCast.class,
        EvaluateArgs.class,
        StaticInitialisation.class,
        MethodCall.class,
        Unpack.class,
        ConstructorReference.class,
        ForUpdates.class,
        ProgramTransformer.class,
        ProgramElement.class,
        Then.class,
        SynchronizedBlock.class,
        ArrayDeclaration.class,
        TypeOperator.class,
        Extends.class,
        ArrayReference.class,
        DoBreak.class,
        SuperReference.class,
        Catch.class,
        TypeReferenceImp.class,
        TypeOf.class,
        LocationVariable.class,
        Expression.class,
        ExpandMethodBody.class,
        SpecialConstructorReference.class,
        ForToWhile.class,
        PostWork.class,
        SwitchToIf.class,
        JavaStatement.class,
        ArrayDeclaration.class,
        MethodReference.class,
        ThisConstructorReference.class,
        ProgramSV.class,
        MethodDeclaration.class,
        DoubleLiteral.class,
        EnhancedFor.class,
        ProgramConstruct.class,
        Default.class,
        FreeLiteral.class,
        Literal.class,
        InheritanceSpecification.class,
        ThisConstructorReference.class,
        FieldReference.class,
        SpecialConstructorCall.class,
        CcatchReturnValParameterDeclaration.class,
        ClassInitializer.class,
        Assert.class,
        PostWork.class,
        Break.class,
        InitArrayCreation.class,
        TypeDeclaration.class,
        ExpandMethodBody.class,
        CcatchBreakWildcardParameterDeclaration.class,
        VariableDeclaration.class,
        CreateObject.class,
        InitArray.class,
        IExecutionContext.class,
        SchematicFieldReference.class,
        JmlAssert.class,
        VariableNamer.IndProgramElementName.class,
        Assignment.class,
        MethodCall.class,
        Try.class,
        ConstructorCall.class,
        ProgramConstruct.class,
        Do.class,
        CcatchReturnValParameterDeclaration.class,
        IsStatic.class,
        MethodReference.class,
        ExpandMethodBody.class,
        PostWork.class,
        ConstructorDeclaration.class,
        If.class,
        FieldReference.class,
        SuperConstructorReference.class,
        VariableNamer.IndProgramElementName.class,
        Exec.class,
        FieldDeclaration.class,
        CreateObject.class,
        LoopStatement.class,
        Import.class,
        ProgramConstruct.class,
        Case.class,
        UnwindLoop.class,
        Catch.class,
        EmptyMapLiteral.class,
        VariableReference.class,
        MethodReference.class,
        TypeOperator.class,
        TypeCast.class,
        CreateObject.class,
        JavaNonTerminalProgramElement.class,
        TypeReferenceImp.class,
        ArrayPostDecl.class,
        DoBreak.class,
        ForInitUnfoldTransformer.class,
        TypeScope.class,
        ForInitUnfoldTransformer.class,
        IsStatic.class,
        ClassDeclaration.class,
        EmptySetLiteral.class,
        ProgramSV.class,
        Switch.class,
        VariableDeclaration.class,
        ForToWhile.class,
        MultipleVarDecl.class,
        SuperArrayDeclaration.class,
        StaticInitialisation.class,
        ConstructorDeclaration.class,
        TypeOf.class,
        InitArray.class,
        MethodBodyStatement.class,
        SpecialConstructorCall.class,
        CcatchBreakLabelParameterDeclaration.class,
        ClassInitializer.class,
        Guard.class,
        Statement.class,
        InterfaceDeclaration.class,
        ConstructorCall.class,
        Unpack.class,
        MethodDeclaration.class,
        ArrayPostDecl.class,
        TypeOf.class,
        EvaluateArgs.class,
        SwitchToIf.class,
        MultipleVarDecl.class,
        JumpStatement.class,
        ConstructorDeclaration.class,
        ClassDeclaration.class,
        FieldSpecification.class,
        MethodBodyStatement.class,
        ProgramSV.class,
        RealLiteral.class,
        BinaryOperator.class,
        Then.class,
        SpecialConstructorCall.class,
        For.class,
        Unpack.class,
        StringLiteral.class,
        MethodDeclaration.class,
        TypeDeclarationContainer.class,
        Literal.class,
        BooleanLiteral.class,
        StatementBlock.class,
        CcatchContinueLabelParameterDeclaration.class,
        MultipleVarDecl.class,
        LocalVariableDeclaration.class,
        Reference.class,
        TypeRef.class,
        MultipleVarDecl.class,
        ReattachLoopInvariant.class,
        MethodDeclaration.class,
        MultipleVarDecl.class,
        EnhancedFor.class,
        Conditional.class,
        UnwindLoop.class,
        SpecialConstructorReference.class,
        EnhancedForElimination.class,
        While.class,
        DoBreak.class,
        MethodFrame.class,
        ArrayLengthReference.class,
        SpecialConstructorReference.class,
        IsStatic.class,
        Else.class,
        ProgramTransformer.class,
        MethodCall.class,
        NameReference.class,
        ForUpdates.class,
        ConstructorCall.class,
        ConstructorDeclaration.class,
        MethodReference.class,
        Assert.class,
        SwitchToIf.class,
        ArrayPostDecl.class,
        FieldSpecification.class,
        InitArrayCreation.class,
        UnwindLoop.class,
        Exec.class,
        TypeOf.class,
        TypeRef.class,
        EvaluateArgs.class,
        DoBreak.class,
        CcatchContinueParameterDeclaration.class,
        ProgramSV.class,
        EnhancedForElimination.class,
        ProgramConstruct.class,
        ProgramMethod.class,
        MethodName.class,
        Default.class,
        ProgramTransformer.class,
        Case.class,
        NewArray.class,
        Ccatch.class,
        Switch.class,
        MethodCall.class,
        ProgramConstant.class,
        PackageReferenceContainer.class,
        TypeReferenceInfix.class,
        DoBreak.class,
        InitArrayCreation.class,
        StatementBlock.class,
        ProgramConstruct.class,
        FieldDeclaration.class,
        FieldReference.class,
        ExpandMethodBody.class,
        Finally.class,
        SuperArrayDeclaration.class,
        Do.class,
        AbstractIntegerLiteral.class,
        MethodCall.class,
        ExpandMethodBody.class,
        Extends.class,
        SchematicFieldReference.class,
        StaticInitialisation.class,
        TypeOf.class,
        LoopStatement.class,
        SpecialConstructorReference.class,
        TypeCast.class,
        DLEmbeddedExpression.class,
        ReattachLoopInvariant.class,
        TypeRef.class,
        IProgramMethod.class,
        CcatchContinueParameterDeclaration.class,
        TypeOf.class,
        MergePointStatement.class,
        CharLiteral.class,
        ConstructorReference.class,
        MultipleVarDecl.class,
        PostWork.class,
        SchemaTypeReference.class,
        ArrayPostDecl.class,
        ScopeDefiningElement.class,
        JavaStatement.class,
        CharLiteral.class,
        TypeRef.class,
        InheritanceSpecification.class,
        EmptyStatement.class,
        SwitchToIf.class,
        SchematicFieldReference.class,
        DoBreak.class,
        Try.class,
        LoopInit.class,
        ExpressionContainer.class,
        IsStatic.class,
        ProgramConstruct.class,
        New.class,
        EmptySetLiteral.class,
        ForInitUnfoldTransformer.class,
        BinaryOperator.class,
        LabeledStatement.class,
        Operator.class,
        MethodDeclaration.class,
        MethodReference.class,
        Extends.class,
        ForToWhile.class,
        IsStatic.class,
        LabeledStatement.class,
        ArrayReference.class,
        PackageReference.class,
        Unpack.class,
        MemberDeclaration.class,
        SpecialConstructorCall.class,
        MemberReference.class,
        TypeReference.class,
        InitArray.class,
        SchematicFieldReference.class,
        ExpandMethodBody.class,
        Throws.class,
        IForUpdates.class,
        SuperReference.class,
        StaticInitialisation.class,
        ExpressionStatement.class,
        TypeRef.class,
        SchematicFieldReference.class,
        InheritanceSpecification.class,
        Catch.class,
        Import.class,
        Catch.class,
        ProgramElementName.class,
        InterfaceDeclaration.class,
        Instanceof.class,
        New.class,
        Continue.class,
        ProgramSV.class,
        SchematicFieldReference.class,
        Implements.class,
        Ccatch.class,
        Return.class,
        PackageSpecification.class,
        TypeOperator.class,
        TypeReferenceImp.class,
        Branch.class,
        Operator.class,
        Exec.class,
        ReattachLoopInvariant.class,
        ForToWhile.class,
        NamedProgramElement.class,
        MethodFrame.class,
        VariableSpecification.class,
        BranchImp.class,
        CreateObject.class,
        Try.class,
        BinaryOperator.class,
        ProgramConstant.class,
        ProgramVariable.class,
        Switch.class,
        MethodFrame.class,
        Guard.class,
        CcatchReturnValParameterDeclaration.class,
        InitArray.class,
        Assert.class,
        EnhancedForElimination.class,
        EnhancedForElimination.class,
        SchematicFieldReference.class,
        ConstructorReference.class,
        ConstructorDeclaration.class,
        SwitchToIf.class,
        SuperConstructorReference.class,
        Guard.class,
        ArrayDeclaration.class,
        ProgramVariable.class,
        ProgramMethod.class,
        IsStatic.class,
        IsStatic.class,
        MergePointStatement.class,
        For.class,
        StaticInitialisation.class,
        ProgramTransformer.class,
        MultipleVarDecl.class,
        SchemaTypeReference.class,
        EnumClassDeclaration.class,
        TypeRef.class,
        FieldDeclaration.class,
        MetaClassReference.class,
        LocalVariableDeclaration.class,
        IGuard.class,
        ProgramVariableName.class,
        ProgramConstruct.class,
        SchemaTypeReference.class,
        Else.class,
        ProgramConstruct.class,
        Continue.class,
        TypeRef.class,
        TypeRef.class,
        ReattachLoopInvariant.class,
        ConstructorCall.class,
        EnumClassDeclaration.class,
        Do.class,
        MethodCall.class,
        ArrayLengthReference.class,
        SchematicFieldReference.class,
        PostWork.class,
        EmptyStatement.class,
        SpecialConstructorCall.class,
        Break.class,
        ForUpdates.class,
        ArrayPostDecl.class,
        EvaluateArgs.class,
        InitArray.class,
        MethodDeclaration.class,
        TypeReferenceImp.class,
        Unpack.class,
        InitArray.class,
        MethodReference.class,
        ReattachLoopInvariant.class,
        ProgramConstruct.class,
        IsStatic.class,
        JavaDeclaration.class,
        Catch.class,
        ProgramPrefix.class,
        SuperReference.class,
        LabelJumpStatement.class,
        Throw.class,
        TypeReference.class,
        CatchAllStatement.class,
        InitArray.class,
        ClassInitializer.class,
        TypeRef.class,
        BranchImp.class,
        TransactionStatement.class,
        ParameterContainer.class,
        VariableScope.class,
        StatementContainer.class,
        TypeReferenceContainer.class,
        TerminalProgramElement.class,
        Modifier.class,
        CcatchReturnParameterDeclaration.class,
        VariableNamer.PermIndProgramElementName.class,
        Declaration.class,
        JavaProgramElement.class,
        LongLiteral.class,
        ParameterDeclaration.class,
        ILoopInit.class,
        ReferenceSuffix.class,
        CcatchNonstandardParameterDeclaration.class,
        EmptySeqLiteral.class,
        AbstractProgramElement.class,
        VariableNamer.TempIndProgramElementName.class));

    public static void main(String[] args) throws FileNotFoundException {
        var all = new TreeSet<Class<?>>(Comparator.comparing(Class::getName));
        all.addAll(allClasses);

        System.out.println(all.size());
        var cu = new com.github.javaparser.ast.CompilationUnit();

        for (var clazz : all) {
            var r = new ClassOrInterfaceDeclaration();
            r.setName(clazz.getSimpleName());
            if (clazz.getSuperclass() != null) {
                r.getExtendedTypes()
                        .add(new ClassOrInterfaceType(null, clazz.getSuperclass().getSimpleName()));
            }

            if (clazz.accessFlags().contains(AccessFlag.ABSTRACT)) {
                r.addModifier(com.github.javaparser.ast.Modifier.DefaultKeyword.ABSTRACT);
            }

            for (var declaredField : clazz.getDeclaredFields()) {
                if (declaredField.isSynthetic()
                        || declaredField.accessFlags().contains(AccessFlag.STATIC)
                        || declaredField.accessFlags().contains(AccessFlag.PRIVATE))
                    continue;

                String type;
                if (declaredField.getType().getTypeParameters().length == 0)
                    type = declaredField.getType().getSimpleName();
                else {
                    type = declaredField.getGenericType().toString();
                    int j = type.lastIndexOf('<');
                    int i = type.lastIndexOf('.', j);
                    type = type.substring(i + 1);
                }
                System.out.println(type);
                r.addField(type, declaredField.getName());
            }


            cu.addType(r);
        }

        try (var out =
            new PrintWriter(new File("key.ncore.java/src/adt/java-ast.java").getAbsoluteFile())) {
            out.write(cu.toString());
        }
    }
}
