/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Mar 28 13:47:08 CET 2008
 */
package java.util;

public interface ListIterator extends java.util.Iterator
{
    //@ public instance ghost \seq seq;
    //@ public instance ghost \bigint index;
    
    //@ public instance invariant 0 <= index && index <= seq.length;

    /*@ public normal_behavior
      @ ensures \result == true <==> index < seq.length;
      @ assignable \strictly_nothing;
      @ determines \result \by seq.length, index;
      @*/
    public boolean hasNext();
    
    /*@ public behavior
      @ requires index < seq.length;
      @ ensures \result == ((Object)seq[\old(index)]);
      @ ensures index == \old(index) + 1;
      @ assignable index;
      @ signals_only java.lang.RuntimeException;
      @ determines \result \by seq, index;
      @ determines index \by \itself;
      @*/
    public /*@nullable@*/ Object next();
    
   public boolean hasPrevious();
   public java.lang.Object previous();
   public int nextIndex();
   public int previousIndex();
   public void remove();
   public void set(java.lang.Object arg0);
   public void add(java.lang.Object arg0);
}
