<h3>Overview:</h3>
<ul>
    <li>Bundle: $cd.Pbh.zipName$</li>
    <li>Date: $cd.checkDate$</li>
    <li>Overall Status: </li>
    <li>Contracts proven: </li>
    <li>Standard output:<br>
        <div style="background-color:#002b36;
                    color:#93a1a1;
                    font-family:monospace;
                    font-size:16px;
                    width:max-content;">
            <pre>$cd.messages; separator=dataView.lineSeparator$</pre>
        </div>
    </li>
</ul>

