/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Mar 28 13:47:08 CET 2008
 */
package java.lang;

public abstract class Enum extends java.lang.Object implements java.lang.Comparable, java.io.Serializable
{

   public final java.lang.String name();
   public final int ordinal();
   protected Enum(java.lang.String arg0, int arg1);
   public java.lang.String toString();
   public final boolean equals(java.lang.Object arg0);
   public final int hashCode();
   protected final java.lang.Object clone() throws java.lang.CloneNotSupportedException;
   public final int compareTo(java.lang.Enum arg0);
// public final java.lang.Class getDeclaringClass();
// public static java.lang.Enum valueOf(java.lang.Class arg0, java.lang.String arg1);
   protected final void finalize();
   public int compareTo(java.lang.Object arg0);
}
