<tr>
    <td>$data.proof.name$</td>
    <td>$data.sourceFile$</td>
    <td>$data.contract.name$</td>
    <td>$data.proofFile$</td>
    <td>$data.proof.settings.choiceSettings.choices.keys$ $!:{c | $c$<br>}!$</td>
    <td></td>
    <td>TODO</td>
    <td>Nodes: $data.proof.statistics.nodes$ <br>
        Interactive Steps: $data.proof.statistics.interactiveSteps$ <br>
        Automode Time: $data.proof.statistics.autoModeTimeInMillis$ ms <br>
    </td>
</tr>