<tr>
    <td>$data.proof.name$</td>
    <td>$data.sourceFile$</td>
    <td>$data.contract.name$</td>
    <td>$data.proofFile$</td>
    <!-- TODO
    <td>$data.proof.settings.choiceSettings.category2Choices.keys:{c | $data.proof.settings.choiceSettings.category2Choices.(c)$<br>}$</td>
    -->
    <td></td>
    <td>TODO</td>
    <td>Nodes: $data.proof.statistics.nodes$ <br>
        Interactive Steps: $data.proof.statistics.interactiveSteps$ <br>
        Automode Time: $data.proof.statistics.autoModeTimeInMillis$ ms <br>
    </td>
</tr>