name: Update Symbex Oracles

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  optional-tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: --continue -D UPDATE_TEST_ORACLE=true -D ORACLE_DIRECTORY=key.core.symbolic_execution/src/test/resources/testcase :key.core.symbolic_execution:test

      - name: Make new branch
        uses: EndBug/add-and-commit@v9
        with:
          add: 'key.core.symbolic_execution/src/test/resources/testcase'
          author_name: Kiki
          author_email: support@kit.edu
          default_author: github_actions
          message: 'Auto-Commit: update of the symbex oracle'
          pull: '--rebase --autostash'
          new_branch: update_oracle_${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}

      - name: Create Pull-Request
        run: gh pr create --title "Update of the symbex oracle" --body "This is an automated Pull Request" -a "unp1" -B "main" -l "automatic" -H update_oracle_${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}
