/* This file has been generated by Stubmaker (de.uka.ilkd.stubmaker)
 * Date: Fri Mar 28 13:47:08 CET 2008
 * 
 * Enriched by JML specifications by MU
 *
 */

package java.lang;

public class Throwable extends java.lang.Object implements java.io.Serializable
{

   //@ protected nullable ghost String message = null;
   //@ protected nullable ghost Throwable cause = null;

   /*@ public normal_behavior
     @    requires true;
     @    ensures message == null && cause == null;
     @    assignable message, cause;
     @*/
   public Throwable() { }

   /*@ public normal_behavior
     @    requires true;
     @    ensures message == arg0 && cause == null;
     @    assignable message, cause;
     @*/
   public Throwable(java.lang.String arg0) {
       this(arg0, null);
   }
   
   /*@ public normal_behavior
     @    requires true;
     @    ensures message == arg0 && cause == arg1;
     @    assignable message, cause;
     @*/
   public Throwable(java.lang.String arg0, java.lang.Throwable arg1) {
       //@ set message = arg0;
       //@ set cause = arg1;
   }
   
   /*@ public normal_behavior
     @    requires true;
     @    ensures message == null && cause == arg0;
     @    assignable message, cause;
     @*/
   public Throwable(java.lang.Throwable arg0) {
       this(null, arg0);
   }
   
   /*@ public normal_behavior
     @    ensures \result == message;
     @*/
   public /*@strictly_pure*/ java.lang.String getMessage();
   
   public java.lang.String getLocalizedMessage();
      
   /*@ public normal_behavior
     @    ensures \result == cause;
     @*/
   public java.lang.Throwable getCause();

   //TODO: fix the contract to match Java's behavior (e.g. arg0 != this or exception)
   /*@ public normal_behavior
     @    requires cause == null;
     @    ensures \result == this && cause == arg0;
     @    assignable cause;
     @ helper // needs to be helper because called in constructor
     @*/
   public java.lang.Throwable initCause(java.lang.Throwable arg0) {
       //@ set cause = arg0;
       return this;
   }
   
   public java.lang.String toString();
   public void printStackTrace();
// public void printStackTrace(java.io.PrintStream arg0);
// public void printStackTrace(java.io.PrintWriter arg0);
   public java.lang.Throwable fillInStackTrace();
// public java.lang.StackTraceElement[] getStackTrace();
// public void setStackTrace(java.lang.StackTraceElement[] arg0);
}
